import { IsNotEmpty, IsString, IsUUID, MaxLength } from 'class-validator';

export class CreateOrderDto {
  /**
   * The delivery address to use for this order.
   * Must be an address belonging to the authenticated customer.
   */
  @IsUUID()
  addressId: string;

  /**
   * Client-generated unique key to prevent duplicate orders on retry.
   * If an order with this key already exists, the server returns the
   * existing order instead of creating a duplicate (409 Conflict).
   *
   * Recommended: UUID v4 generated by the client before submission.
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  idempotencyKey: string;
}
